# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2GadQflNx3uNRsYDFEZ1iVWgI74Y6fY
"""

import pandas as pd
import plotly.express as px

df = px.data.gapminder()
df = df.dropna()
df.head()

df.info()

print("\n--- Verificando linhas duplicadas ---")
tota_duplicados = df.duplicated().sum()
print(f"Total de linhas duplicadas: {tota_duplicados}")

df_media_ano_continentes = df.groupby(['year', 'continent'])['lifeExp'].mean().reset_index()
fig = px.line(df_media_ano_continentes, x='year', y='lifeExp', color='continent', title='Evolução da Expectativa de Vida por Continente')
fig.show()

df_media_ano_mundial = df.groupby('year')['lifeExp'].mean().reset_index()
fig = px.line(df_media_ano_mundial, x='year', y='lifeExp', title='Evolução da Expectativa de Vida Mundial')
fig.show()

df_evolucao_pib = df.groupby(['year', 'continent'])['gdpPercap'].mean().reset_index()
fig = px.line(df_evolucao_pib, x='year', y='gdpPercap', color='continent', title='Evolução do PIB per capita por Continente')
fig.show()

df_2007 = df[df['year'] == 2007]
df_2007.loc[df_2007.groupby('continent')['pop'].idxmax()]
fig = px.bar(df_2007, x='continent', y='pop', title='População por Continente em 2007')
fig.show()

print()

fig = px.bar(df_2007, x='continent', y='gdpPercap', title='PIB per capita por Continente em 2007')
fig.show()

print()


fig = px.scatter(df_2007, x='gdpPercap', y='lifeExp', color='continent', title='Relação entre PIB per capita e Expectativa de Vida em 2007')
fig.show()

df_pais_mais_populoso_2007 = df_2007.sort_values(by='pop', ascending=False).head(10)
px.bar(df_pais_mais_populoso_2007, x='country', y='pop', title='Países mais Populares em 2007')

df_1952 = df[df['year'] == 1952]
df_1952.loc[df_1952.groupby('continent')['pop'].idxmax()]

fig = px.bar(df_1952, x='continent', y='pop', title='População por Continente em 1952')
fig.show()

print()

fig = px.bar(df_1952, x='continent', y='gdpPercap', title='PIB per capita por Continente em 1952')
fig.show()

print()

fig = px.scatter(df_1952, x='gdpPercap', y='lifeExp', color='continent', title='Relação entre PIB per capita e Expectativa de Vida em 1952')
fig.show()

fig = px.scatter(df, x='gdpPercap', y='lifeExp', color='continent', title='Relação entre PIB per capita e Expectativa de Vida')
fig.show()

fig = px.scatter(df, x='gdpPercap', y='lifeExp', animation_frame="year", animation_group="country",
           size="pop", color="continent", hover_name="country",
           log_x=True, size_max=55, range_y=[25,90], title="A Evolução da Riqueza e Saúde no Mundo (1952-2007)")
fig.show()

fig = px.choropleth(df, locations="iso_alpha", color="lifeExp", hover_name="country", animation_frame="year", range_color=[20 ,80], title="Expectativa de Vida por País")
fig.show()

df_brasil = df[df['country'] == 'Brazil'].copy()
df_brasil['gdpTotal'] = df_brasil['gdpPercap'] * df_brasil['pop']

fig = px.line(df_brasil, x='year', y='lifeExp', title='Evolução da Expectativa de Vida no Brasil')
fig.show()

print()
print()

fig = px.line(df_brasil, x='year', y='gdpTotal', title='Evolução do PIB per capita no Brasil')
fig.show()

px.box(df_2007, x='continent', y='lifeExp', title='Distribuição da Expectativa de Vida por Continente')

import seaborn as sns
import matplotlib.pyplot as plt

df_corr = df.corr(numeric_only=True)
sns.heatmap(df_corr, annot=True, cmap='coolwarm', fmt='.2f')

plt.title('Correlação entre Variáveis Numéricas')
plt.show()